services:
  api:
    image: libre-chat
    container_name: LibreChat
    ports:
      - "3080:3080"
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile.multi
      target: api-build
    platform: linux/arm64
    restart: always
    user: "1000:1000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      - CUSTOM_FOOTER=AI Copywriter
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - SEARCH=false
      - MEILI_NO_ANALYTICS=true
      - MEILI_HOST=http://meilisearch:7700
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs
      - ./data:/app/api/data
  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.12.3
    restart: always
    # ports: # Uncomment this to access meilisearch from outside docker
    #   - 7700:7700 # if exposing these ports, make sure your master key is not the default value
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./meili_data_v1.12:/meili_data
  mongodb:
    container_name: chat-mongodb
    image: mongo
    restart: always
    user: "1000:1000"
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
